### ISSUE TITLE
1

### ISSUE THREAD

**Issue by W1ndys** [W1ndys/Github-actions-study#38]
1

**Comment by W1ndys** [comment]
GitHub Actions 是一个强大的工具，它允许你自动化许多与 GitHub 仓库相关的任务。要实现你描述的功能，即当有新的 issue 被打开时，自动在该 issue 下发表与 issue 内容相同的评论，你可以创建一个 GitHub Actions 工作流（workflow）。

下面是一个基本的示例工作流，它使用 `issues` 事件触发，并在新的 issue 被创建时运行一个脚本，将 issue 的内容作为评论发布：

```yaml
name: Auto Comment on Issue
on: [issues]

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Auto comment on issue
      uses: actions/github-script@v4
      with:
        script: |
          const issue_number = context.payload.issue.number;
          const issue_title = context.payload.issue.title;
          const issue_body = context.payload.issue.body;
          const token = process.env.GITHUB_TOKEN;
          const repository = context.repo;

          // 使用 GitHub API 发布评论
          const commentBody = `Issue #${issue_number} opened with the following content:\n\nTitle: ${issue_title}\n\nBody: ${issue_body}`;

          github.rest.issues.createComment({
            owner: repository.owner,
            repo: repository.repo,
            issue_number: issue_number,
            body: commentBody
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

这个工作流的关键点如下：

1. `on: [issues]` 表示这个工作流会在 issues 事件发生时触发，这包括 issue 被打开、关闭、重新打开等。
2. `jobs` 下定义了一个名为 `auto-comment` 的作业。
3. `runs-on: ubuntu-latest` 指定了运行这个作业的操作系统环境。
4. `steps` 下定义了作业需要执行的步骤。
5. 第一个步骤 `uses: actions/checkout@v2` 用于检出仓库的代码，这在某些情况下可能是必要的，但在这个特定的例子中，我们不需要它，因为我们不打算修改仓库的代码。
6. 第二个步骤 `uses: actions/github-script@v4` 使用 `github-script` 来运行一个脚本，这个脚本使用 GitHub API 发布评论。
7. `script` 部分包含了实际的 JavaScript 代码，它获取 issue 的编号、标题和内容，并将这些信息格式化为一条评论。
8. `env` 下定义了一个环境变量 `GITHUB_TOKEN`，它使用 `${{ secrets.GITHUB_TOKEN }}` 来引用存储在仓库设置中的密钥。

请注意，你需要在 GitHub 仓库的设置中设置一个 `GITHUB_TOKEN` 密钥，以便工作流可以以仓库的身份进行操作。

此外，确保你正确配置了仓库的权限，以便 `GITHUB_TOKEN` 能够创建评论。

将上述 YAML 代码保存为 `.github/workflows/auto-comment-on-issue.yml` 并推送到你的仓库，这样每当有新的 issue 被打开时，这个工作流就会自动运行。
